baseURL = 'https://blog.Irvingou.com/'
languageCode = 'en-us'
title = 'Irvings Blog'
theme = "paper"


[params]
  # color style
  color = 'wheat'                           # linen, wheat, gray, light

  # header social icons
  github = 'Irvingouj'                 
  linkedin = 'irving-ou-8b195b1b1'          
  #rss = true                                # show rss icon

  # home page profile
  avatar = 'oujunyiirving@gmail.com'                 # gravatar email or image url
  name = 'Irving Ou'
  bio = 'He who has a why to live for can bear almost any how'


  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTeX math typesetting globally
  comments = false     